services:
  openchamber:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openchamber
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - openchamber_config:/home/openchamber/.config/openchamber
      - opencode_share:/home/openchamber/.local/share/opencode
      - opencode_state:/home/openchamber/.local/state/opencode
      - opencode_config:/home/openchamber/.config/opencode
      - ssh_data:/home/openchamber/.ssh
      - workspaces_data:/home/openchamber/workspaces
    environment:
      OPENCHAMBER_HOST: 0.0.0.0  # Bind address (default in Docker: 0.0.0.0)
      UI_PASSWORD: ${UI_PASSWORD:?}  # Uncomment to set UI password
      OH_MY_OPENCODE: true # enable oh-my-opencode
    restart: unless-stopped

volumes:
  openchamber_config:
  opencode_share:
  opencode_state:
  opencode_config:
  ssh_data:
  workspaces_data: